# Schlauerlauer

stages:
  - hugo-build
update-website:
  stage: hugo-build
  only:
    - master
  allow_failure: false
  image: "alpine:3.9.4"
  before_script:
  # $GIT_SSH_PRIV_KEY: base64 encoded one-liner
    - 'which ssh-agent || (apk update && apk --no-cache add openssh-client git libc6-compat libstdc++)'
    - eval $(ssh-agent -s)
    - echo $GIT_SSH_PRIV_KEY | base64 -d > tmp.key
    - chmod 400 tmp.key
    - ssh-add tmp.key
    - rm tmp.key
    - mkdir -p ~/.ssh
    - ssh-keyscan gitlab.com >> gitlab-known-hosts
    - cat gitlab-known-hosts >> ~/.ssh/known_hosts
    - 'git config --global user.email "$GIT_EMAIL" && git config --global user.name "$GIT_USER"'
    - rm -rf public
    - mkdir hugo && cd hugo
    - wget -O hugo.tar.gz $HUGO_LINK
    - tar -xzf hugo.tar.gz
    - mv hugo /usr/bin && cd ..
    - rm -rf hugo
  script:
    - hugo
    - mv public ../
    - git remote set-url origin git@gitlab.com:schlauerlauer/website.git
    - git stash && git stash drop
    - git checkout public
    - rm -rf public
    - mv ../public .
    - git add -A
    - git commit -m "$GIT_USER"
    - git push